export const generalConstructionReviews_1 = [
  "I got quotes from six different contractors before landing on {{companyName}}. From the first call, they were the most professional and transparent. Their pricing was fair—definitely not the cheapest, but the materials and craftsmanship blew the others out of the water. You get what you pay for, and then some. The project involved a full bathroom remodel, and every fixture and tile was installed perfectly. The crew was punctual, respectful, and cleaned up after themselves each day. I also appreciated that they assigned a dedicated project manager who kept us updated daily. <br/><br/>Any questions we had were answered promptly, and change orders were handled with full clarity and documentation. They even followed up two weeks after completion to make sure everything was to our satisfaction. We’ve already recommended them to two of our neighbors and would gladly hire them again.",

  "I almost didn’t reach out because I assumed they’d be out of our budget, but {{companyName}} surprised me. Their pricing was competitive, and they explained where the money was going in a way that actually made sense. No fluff, just real value. I felt good about every dollar we spent.",

  "We hired {{companyName}} to remodel our kitchen and ended up using them again for our backyard project six months later. Their team was punctual, courteous, and cleaned up every single day. The results speak for themselves, and the warranty gave us added peace of mind. Easily one of the best contractor experiences we’ve had. If you get to choose, we worked with {{salespersonName}} and we absolutely loved him! He was detail-oriented and had a great design eye—he caught a few things in our layout that we would’ve missed. The kitchen turned out like something out of a magazine, with custom cabinetry, under-cabinet lighting, and a waterfall-edge island. For the backyard, they built a pergola, installed pavers, and even helped us with outdoor lighting. Everything was completed ahead of schedule and under budget. We’ve since hosted multiple gatherings, and guests always ask who did the work.",

  "Our first project with {{companyName}} was over four years ago, and they still stand behind their work. We had a minor issue with a door frame shifting, and they came out within the week to make it right—at no charge. That kind of follow-through is rare, and it’s exactly why we’ll continue to recommend them. Over the years, they’ve worked on several areas of our home, including repairing drywall, repainting interiors, and building a custom storage solution in our garage. Each time, they’ve brought the same level of quality and professionalism. Even when materials were delayed during our second project, they communicated clearly and adjusted the schedule to keep us on track. I’ve never had to chase them for updates, which says a lot. Their project managers are organized, responsive, and genuinely care about the outcome. We’ll continue to use them as our go-to contractor.",

  "I can’t overstate how smooth the process was. {{salespersonName}} gave us a clear timeline, delivered everything on schedule, and the final price matched the estimate—no surprises. We had them redo our floors and add custom shelving, and everything turned out beautifully. You can tell they actually care about the end result. The flooring crew went out of their way to match the existing trim perfectly, and even made a few small repairs at no additional charge. The custom shelves in our home office turned out better than we envisioned, with built-in lighting and soft-close drawers. Communication was stellar throughout, and we received daily photo updates since we were traveling during part of the work. When we got home, the place was spotless and completely turnkey. The walkthrough at the end was thorough, and any punch list items were addressed within 48 hours. We’ll absolutely be hiring them again for our upcoming master bath renovation.",

  "From demolition to final inspection, the team at {{companyName}} stayed on top of everything. We had a full home renovation, and the entire project finished ahead of schedule. They helped with permits, coordinated with inspectors, and kept the work site safe and organized. Total pros.",

  "After being burned by a previous contractor, I was extremely cautious this time around. {{companyName}} took the time to walk me through their process, show me examples of similar projects, and provided a detailed scope of work. Their communication alone set them apart—and the final result was better than I imagined. I had them remodel my basement into a home gym and guest suite, complete with soundproofing, new flooring, and built-in cabinetry. The attention to detail was top-notch, from the trim work to the lighting layout. There were a few unforeseen issues once they opened up the walls, but they handled everything transparently and didn’t nickel-and-dime me for every change. In fact, they offered a few suggestions that actually saved me money in the end. Every single crew member showed respect for my home, laying down mats and sealing off dust-prone areas. This is the first time I’ve worked with a contractor and felt 100% confident from start to finish.",

  "We’ve used {{companyName}} for three separate projects now—roof replacement, garage conversion, and interior painting. Each time, they’ve been consistent, reliable, and respectful of our home. Their crews are well-trained and it shows in the details. It’s rare to find a construction company you can actually trust long-term. The garage conversion turned out especially well, with added insulation, plumbing for a small kitchenette, and clever use of space to create a multi-purpose room. They were flexible with scheduling, and even when weather delayed the roof install, they communicated and adjusted seamlessly. What really stood out was how they kept track of our preferences from past projects—paint colors, finish styles, etc.—and incorporated those into the new work without us even having to ask. The team made it feel like we were working with an old friend who just happened to be a pro contractor. We won’t be calling anyone else in the future.",

  "The thing that really won me over was how much pride {{companyName}} takes in their work. Our patio and outdoor kitchen look amazing, but it’s the small touches—like how they handled drainage and lighting—that made the difference. They didn’t cut corners, and they didn’t treat us like just another job.",

  "We recently completed a home addition with {{companyName}}, and we couldn’t be happier. The new space blends perfectly with the original structure—something I was really worried about. The design team was patient, and the builders were incredibly skilled. They even followed up a month later to check if we needed anything else.",
];

export const generalConstructionReviews_2 = [
  "I interviewed five contractors before choosing {{companyName}}. They weren’t the cheapest, but they were the only ones who took the time to really understand what I wanted. That made all the difference. {{salespersonName}} sat down with me, reviewed my design ideas, and even made some great suggestions that improved the layout and functionality. Their crew showed up exactly when they said they would, communicated every step clearly, and kept the space surprisingly tidy for an active job site. The materials were top-notch, the team respected my home, and the final results exceeded my expectations. Even months later, everything still looks fresh and well-crafted. I had one small concern with a door alignment and they came out the same week to fix it—no hesitation. That level of care is rare, and I wouldn't hesitate to recommend them again.",

  "I was just called, 2 years later, and was asked if I'm still satisfied with everything. It just reminded me how much of a pleasant experience it was having them help us with our home renovation. It’s been about 2 years since our full bathroom remodel, and everything still looks brand new. When {{salespersonName}} called to check-in I immediately felt like writing this review is well deserved. They used quality finishes and made sure everything was sealed properly. We had a minor plumbing issue about 8 months ago, and even though it wasn’t their fault, they sent someone out to fix it. Amazing 5/5 experience all around",

  "My wife and I were worried about construction dragging on and going over budget. But {{companyName}} kept things tight and efficient. The pricing was fair, and they never tried to upsell us. We knew exactly what to expect, and that peace of mind was priceless. From day one, {{salespersonName}} laid out a transparent schedule and scope of work, and they delivered on every promise. They handled permits and inspections without us lifting a finger, and even when we made a couple of mid-project changes, they worked them in smoothly without slowing anything down. The team was courteous and cleaned up at the end of each day—a small touch that made a big difference. It's been 18 months since the renovation, and everything still looks and functions perfectly. We couldn’t be happier with the experience or the outcome.",

  "We had {{companyName}} add a master suite to our home, and the project came out beautifully. What impressed me most was their attention to structural integrity—something other contractors barely mentioned. The inspector even commented on how clean and precise the framing was. {{salespersonName}} was detail-oriented and made sure we understood all the trade-offs in layout and material decisions. We appreciated that they provided us with a detailed project calendar, which they actually stuck to. The finishes in the bathroom are hotel-level, and the lighting design made the space feel larger than it is. They even custom-built a bench for the walk-in shower after we casually mentioned the idea during a site visit. That kind of attention to detail is rare. We love our new suite and are planning to use them again for a deck project later this year.",

  "Four years after our garage conversion, I had a concern about some minor settling. I emailed {{companyName}}, expecting a brush-off—but they came out, assessed it, and made adjustments at no charge. That kind of long-term accountability is rare. I'd hire them again in a heartbeat. The original project had turned our underused garage into a guest suite with a small kitchenette and bathroom, and it still looks and functions like new. During the build, they worked efficiently and were respectful of our family's schedule, even pausing noisy work when our baby was napping. The finish work was immaculate and the project wrapped up exactly when they said it would. We had friends stay over during the holidays last year, and they couldn’t believe it used to be a garage. I don’t think we’ll ever use another contractor again.",

  "I needed someone to do a complete kitchen overhaul, and {{companyName}} came highly recommended. They helped us select durable, modern finishes that still stayed within our budget. The tile work was flawless, and the cabinetry looks like something out of a magazine. Can’t stop staring at it. {{salespersonName}} went above and beyond to source materials that matched our inspiration photos, and they even brought in a lighting consultant to help with the final layout. When our old plumbing turned out to be in worse shape than expected, they fixed it without delay and kept us informed on the added cost in real time—no surprises. The crew showed up early, stayed late when needed, and kept the space livable throughout the process. It's been over a year and everything is still in perfect condition. I’ve never been so happy with a renovation.",

  "The pricing was very reasonable, especially considering the quality of the work. We had our roof and fascia redone, and {{companyName}} used better materials than some of the other quotes we received. The crew was on-time and cleaned up thoroughly after each day. Solid company from start to finish.",

  "We did a complete home exterior makeover—new siding, windows, and a fresh coat of paint. {{salespersonName}} coordinated every detail and kept us in the loop the whole time. The finished product turned heads in our neighborhood. People keep asking us who we used! From the first consultation to the final walkthrough, everything was smooth and stress-free. We were especially impressed with how well the crew cleaned up each day and how organized they kept the job site. There were no delays or last-minute surprises—just consistent communication and solid work. Even now, a year later, the paint looks vibrant and the windows operate flawlessly. It’s clear they don’t cut corners. That kind of consistency earns trust, and we’ve since recommended {{companyName}} to family and friends.",

  "We waited years to do this remodel, and I'm glad we waited until we found {{companyName}}. They didn't just build—they advised, guided, and helped us avoid costly mistakes. Their design suggestions added function *and* value to our home. It feels like we’re living in a brand new house.",

  "After getting burned by a contractor that ghosted mid-project, I was extremely skeptical. {{companyName}} restored my faith. They showed up on time, met every milestone, and gave us a beautiful kitchen without a single delay. Truly a rare find in this industry. {{salespersonName}} walked us through every phase of the process, offered realistic timelines, and actually stuck to them. When a small backorder issue came up on our backsplash tile, they offered a great temporary solution to keep things moving, and then came back to install it the moment it arrived. The workmanship on the cabinetry and electrical was top-tier—everything feels solid and looks like something out of a catalog. It’s been over a year and we’re still getting compliments from guests. I now understand why people rave about this company.",
];
